name: Run Watchers

on:
  schedule:
    - cron: "*/30 * * * *"   # 每30分钟运行一次
  workflow_dispatch:          # 手动触发

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run njubs.py
      run: python njubs.py
